"""pw: convert all owner_id emails to lower case, rename user_state table pk to `owner_id`

Revision ID: ec127df018c6
Revises: 25cf90db6d35
Create Date: 2025-09-09 15:54:16.188284

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "ec127df018c6"
down_revision: Union[str, None] = "25cf90db6d35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # update pk name of user_state table to `owner_id`
    op.alter_column("user_state", "user_email", new_column_name="owner_id")

    tables = ["chat", "chat_group", "attachment", "usage_tracking", "user_state"]

    connection = op.get_bind()

    # Update tables
    for table_name in tables:
        connection.execute(
            text(
                f"""UPDATE {table_name}
                SET owner_id = LOWER(owner_id)
                WHERE owner_id != LOWER(owner_id)
                """
            )
        )
        print(f"Updated {table_name}.owner_id to lowercase")

    # Verify no mixed case remains
    for table_name in tables:
        result = connection.execute(
            text(
                f"""SELECT COUNT(*) FROM {table_name}
                WHERE owner_id != LOWER(owner_id)
                """
            )
        ).scalar()

        if result > 0:
            raise Exception(
                f"Verification failed: {table_name} still has {result} mixed case owner_id values"
            )

    print("All owner_id columns successfully converted to lowercase")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_state", "owner_id", new_column_name="user_email")
    print("Cannot restore original casing - no changes made")

    # ### end Alembic commands ###
