"""Add releases table and last_release_date field

Revision ID: 25cf90db6d35
Revises: 65a3145b60d5
Create Date: 2025-08-22 12:05:06.337825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25cf90db6d35'
down_revision: Union[str, None] = '65a3145b60d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('changes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('array_length(changes, 1) <= 50', name='changes_max_length'),
    sa.CheckConstraint('array_length(changes, 1) >= 1', name='changes_min_length'),
    sa.CheckConstraint('char_length(title) > 0', name='release_title_min_length'),
    sa.PrimaryKeyConstraint('release_id')
    )
    op.create_index('idx_release_title_lower', 'releases', [sa.literal_column("lower('title')")], unique=False)
    op.create_index(op.f('ix_releases_date'), 'releases', ['date'], unique=False)
    op.add_column('user_state', sa.Column('last_release_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_state', 'last_release_date')
    op.drop_index(op.f('ix_releases_date'), table_name='releases')
    op.drop_index('idx_release_title_lower', table_name='releases')
    op.drop_table('releases')
    # ### end Alembic commands ###
