"""Added chat group table

Revision ID: 53903683a426
Revises: 1475dcf15094
Create Date: 2025-07-28 11:00:51.831734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53903683a426'
down_revision: Union[str, None] = '1475dcf15094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_group',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(title) > 0', name='chat_title_min_length'),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index('idx_chat_group_title_lower', 'chat_group', [sa.literal_column('lower(title)')], unique=False)
    op.create_index(op.f('ix_chat_group_owner_id'), 'chat_group', ['owner_id'], unique=False)
    op.add_column('chat', sa.Column('group_id', sa.UUID(), nullable=True, comment='Foreign key linking to the group of chats'))
    op.create_index(op.f('ix_chat_group_id'), 'chat', ['group_id'], unique=False)
    op.create_foreign_key(None, 'chat', 'chat_group', ['group_id'], ['group_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')  
    op.drop_index(op.f('ix_chat_group_id'), table_name='chat')  
    op.drop_column('chat', 'group_id')  
    op.drop_index(op.f('ix_chat_group_owner_id'), table_name='chat_group')  
    op.drop_index('idx_chat_group_title_lower', table_name='chat_group')  
    op.drop_table('chat_group') 
    # ### end Alembic commands ###
