"""Add usage tracking table

Revision ID: 65a3145b60d5
Revises: 53903683a426
Create Date: 2025-08-20 03:16:50.601669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a3145b60d5'
down_revision: Union[str, None] = '53903683a426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_tracking',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the usage tracking record'),
    sa.Column('owner_id', sa.String(), nullable=False, comment='Owner email'),
    sa.Column('chat_id', sa.UUID(), nullable=True, comment='Foreign key linking to the chat'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Timestamp of the usage event'),
    sa.Column('model', sa.String(), nullable=False, comment='Model used for the chat'),
    sa.Column('task', sa.String(), nullable=False, comment='Task type, e.g., chat, tool, embedding, etc.'),
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='Number of input tokens used, not counting cache reads or creates'),
    sa.Column('input_cache_read', sa.Integer(), nullable=False, comment='Number of input tokens read from cache'),
    sa.Column('input_cache_create', sa.Integer(), nullable=False, comment='Number of input token cache created'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='Number of output tokens generated'),
    sa.Column('input_cost', sa.Float(), nullable=False, comment='Cost incurred for input tokens'),
    sa.Column('output_cost', sa.Float(), nullable=False, comment='Cost incurred for output tokens'),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_tracking_chat_id', 'usage_tracking', ['chat_id'], unique=False)
    op.create_index('idx_usage_tracking_owner_timestamp', 'usage_tracking', ['owner_id', sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usage_tracking_owner_timestamp', table_name='usage_tracking')
    op.drop_index('idx_usage_tracking_chat_id', table_name='usage_tracking')
    op.drop_table('usage_tracking')
    # ### end Alembic commands ###
