"""pw: add vault models

Revision ID: d9834ecac7fc
Revises: fef3cd1b27d8
Create Date: 2025-05-15 14:45:21.140131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9834ecac7fc'
down_revision: Union[str, None] = 'fef3cd1b27d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_credential',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('encrypted_dek', sa.String(), nullable=False),
    sa.Column('vhash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('vault_session',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('rotate_token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_vault_user_email', 'vault_session', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vault_user_email', table_name='vault_session')
    op.drop_table('vault_session')
    op.drop_table('vault_credential')
    # ### end Alembic commands ###
