"""pw: add chat status

Revision ID: e8e4dad5b79c
Revises: ecaef6354291
Create Date: 2025-06-16 11:32:34.826052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8e4dad5b79c'
down_revision: Union[str, None] = 'ecaef6354291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

chat_status_enum = postgresql.ENUM('normal', 'readonly', name='chatstatusenum')

def upgrade() -> None:
    """Upgrade schema."""
    chat_status_enum.create(op.get_bind())
    op.add_column('chat', sa.Column('status', chat_status_enum, nullable=False, server_default="normal"))
    op.add_column('chat', sa.Column('status_msg', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'status_msg')
    op.drop_column('chat', 'status')
    chat_status_enum.drop(op.get_bind())