"""setup db first time

Revision ID: fef3cd1b27d8
Revises: 
Create Date: 2025-05-08 09:22:13.618742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef3cd1b27d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('attachment_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'ready', 'failed', name='attachmentstatusenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('vault_mode', sa.Boolean(), nullable=False),
    sa.Column('s3_location', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('progress_msg', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index('idx_attchmnt_ownerid', 'attachment', ['owner_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('chat',
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.Column('vault_mode', sa.Boolean(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(title) > 0', name='chat_title_min_length'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index('idx_chat_owner_favorite_created', 'chat', ['owner_id', sa.literal_column('favorite DESC'), sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_chat_owner_vault', 'chat', ['owner_id', 'vault_mode'], unique=False)
    op.create_index('idx_chat_title_lower', 'chat', [sa.literal_column('lower(title)')], unique=False)
    op.create_table('message_metadata',
    sa.Column('checkpoint_id', sa.Text(), nullable=False, comment='The LangGraph checkpoint ID associated with this specific message version.'),
    sa.Column('message_id', sa.UUID(), nullable=False, comment='Unique identifier for a logical message (shared across versions).'),
    sa.Column('chat_id', sa.UUID(), nullable=False, comment='Foreign key linking to the chat session.'),
    sa.Column('role', sa.Enum('AI', 'USER', 'TOOL', name='message_role_enum'), nullable=False, comment='Role of the message sender (user, assistant, tool).'),
    sa.Column('parent_checkpoint_id', sa.Text(), nullable=True, comment='The checkpoint_id of the preceding message in this conversational branch.'),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index('idx_message_chat_id', 'message_metadata', ['chat_id'], unique=False)
    op.create_index('idx_message_message_id', 'message_metadata', ['message_id'], unique=False)
    op.create_table('user_state',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('current_chat_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['current_chat_id'], ['chat.chat_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_state')
    op.drop_index('idx_message_message_id', table_name='message_metadata')
    op.drop_index('idx_message_chat_id', table_name='message_metadata')
    op.drop_table('message_metadata')
    op.drop_index('idx_chat_title_lower', table_name='chat')
    op.drop_index('idx_chat_owner_vault', table_name='chat')
    op.drop_index('idx_chat_owner_favorite_created', table_name='chat')
    op.drop_table('chat')
    op.drop_index('idx_attchmnt_ownerid', table_name='attachment')
    op.drop_table('attachment')
    # ### end Alembic commands ###
