from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pathlib import Path
import os

router = APIRouter()

BASE_AGENT_WORKDIR = os.environ.get("AGENT_MODE_WORKDIR", "/tmp/dish_chat_agent")

@router.get("/artifacts/{chat_id}/{file_path:path}")
async def download_artifact(chat_id: str, file_path: str):
    """
    Download a file artifact generated by the agent.
    
    Args:
        chat_id: The chat/workspace ID
        file_path: Relative path to the file within the workspace
    """
    # Security: ensure the path doesn't escape the workspace
    workspace = Path(BASE_AGENT_WORKDIR) / chat_id
    full_path = (workspace / file_path).resolve()
    
    # Verify the resolved path is still within the workspace
    if not str(full_path).startswith(str(workspace.resolve())):
        raise HTTPException(status_code=403, detail="Access denied")
    
    if not full_path.exists():
        raise HTTPException(status_code=404, detail="File not found")
    
    if not full_path.is_file():
        raise HTTPException(status_code=400, detail="Not a file")
    
    return FileResponse(
        path=str(full_path),
        filename=full_path.name,
        media_type="application/octet-stream"
    )

@router.get("/artifacts/{chat_id}")
async def list_artifacts(chat_id: str):
    """
    List all artifacts in a chat's workspace.
    
    Returns a list of downloadable files with their paths and sizes.
    """
    workspace = Path(BASE_AGENT_WORKDIR) / chat_id
    
    if not workspace.exists():
        return {"artifacts": []}
    
    artifacts = []
    for root, dirs, files in os.walk(workspace):
        for file in files:
            file_path = Path(root) / file
            rel_path = file_path.relative_to(workspace)
            
            artifacts.append({
                "name": file,
                "path": str(rel_path),
                "size": file_path.stat().st_size,
                "download_url": f"/rest/api/v1/agent-mode/artifacts/{chat_id}/{rel_path}"
            })
    
    return {"artifacts": artifacts}
