import Head from 'next/head';
import { GetServerSideProps, GetServerSidePropsResult } from 'next';

import { getChat, getChats } from '@shared/ui/services/chats.services';
import { getChatsGroups } from '@/services/chatGroup.service';

import { wrapper } from '@shared/ui/store';
import {
  setActiveChat,
  setChats,
  setHasMoreChats,
  setHasMoreMessages,
  setTotalChats,
  setVaultMode,
  setVaultModeRegistered,
} from '@shared/ui/store/chats/chats.slice';
import {
  setHasMoreReleases,
  setReleases,
  setShowReleaseModal,
  setUser,
} from '@shared/ui/store/settings/settings.slice';
import { setChatsGroups } from '@shared/ui/store/chatsGroups/chatsGroups.slice';
import { handleServerError } from '@shared/ui/utils/errors.utils';
import {
  CHAT_GROUPS_PAGE_SIZE,
  CHAT_MESSAGES_PAGE_SIZE,
  CHATS_PAGE_SIZE,
} from '@shared/ui/constants/common.constants';
import { fetchUserData } from '@/utils/requests.utils';
import customDayjs from '@shared/ui/libs/dayjs.libs';
import { updateLastReleaseDate } from '@shared/ui/services/releases.services';
import { getMessages } from '@shared/ui/services/messages.services';
import { transformMessagesToObject } from '@shared/ui/utils/messages.utils';

import HomeTemplate from '@/components/templates/HomeTemplate';

import { TemplateErrorProps } from '@shared/ui/interfaces/templates.interfaces';
import { AxiosIncomingClientHeaders } from '@shared/ui/types/axios.types';

const fetchChatsData = async (
  incomingHeaders: AxiosIncomingClientHeaders['incomingHeaders'],
) => {
  const chatsResponse = await getChats({
    page: 1,
    limit: CHATS_PAGE_SIZE,
    incomingHeaders,
  });

  const {
    docs = [],
    hasNextPage = false,
    active_chat_id = null,
    totalDocs = 0,
  } = chatsResponse;

  return { docs, hasNextPage, active_chat_id, totalDocs };
};

const fetchActiveChat = async ({
  activeChatId,
  incomingHeaders,
}: {
  activeChatId: string | undefined;
  incomingHeaders: AxiosIncomingClientHeaders['incomingHeaders'];
}) => {
  if (!activeChatId) return null;

  const chat = await getChat({
    id: activeChatId,
    incomingHeaders,
  });

  if (!chat?.chat_id) return null;

  const { docs = [], hasNextPage = false } = await getMessages({
    chat_id: activeChatId,
    page: 1,
    limit: CHAT_MESSAGES_PAGE_SIZE,
    incomingHeaders,
  });
  return {
    ...chat,
    messages: transformMessagesToObject(docs.reverse()),
    hasMoreMessages: hasNextPage,
    active: true,
  };
};

const fetchChatGroups = async (
  incomingHeaders: AxiosIncomingClientHeaders['incomingHeaders'],
) => {
  const { docs: chatsGroups = [] } = await getChatsGroups({
    page: 1,
    limit: CHAT_GROUPS_PAGE_SIZE,
    incomingHeaders,
  });

  return chatsGroups;
};

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Dish chat - Chat</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomeTemplate />
    </>
  );
};

export const getServerSideProps: GetServerSideProps<TemplateErrorProps> =
  wrapper.getServerSideProps(
    // @ts-ignore
    (store) =>
      // @ts-ignore
      async (ctx): Promise<GetServerSidePropsResult<TemplateErrorProps>> => {
        try {
          // Check if auth is disabled
          const disableAuth = process.env.NEXT_PUBLIC_DISABLE_AUTH === 'true';
          
          let userEmail = 
            ctx?.req?.cookies['userEmail'] ||
            ctx?.req?.headers['x-auth-request-email'];

          // If auth is disabled and no email, use a default test user
          if (disableAuth && !userEmail) {
            userEmail = 'test-user@dish.com';
            console.log('[NO-AUTH MODE] Using default test user:', userEmail);
          }

          if (!userEmail) {
            return {
              redirect: {
                destination: '/403',
                permanent: false,
              },
            };
          }

          const incomingHeaders: AxiosIncomingClientHeaders['incomingHeaders'] =
            {
              ...ctx.req.headers,
              'X-Auth-Request-Email': userEmail,
            };

          // Fetch user data and vault settings
          const { user, isVaultModeRegistered, isVaultModeEnabled, releases } =
            await fetchUserData(incomingHeaders);

          const releasesList = releases?.docs || [];

          // Dispatch user and vault data
          store.dispatch(setUser(user));
          store.dispatch(setVaultModeRegistered(isVaultModeRegistered));
          store.dispatch(setVaultMode(isVaultModeEnabled));
          store.dispatch(setReleases(releasesList));
          store.dispatch(setHasMoreReleases(!!releases?.hasNextPage));
          const lastRelease = releasesList[0];
          if (lastRelease) {
            const lastReleaseDate = user?.last_release_date;
            if (
              !lastReleaseDate ||
              customDayjs(lastRelease.date).isAfter(
                customDayjs(lastReleaseDate),
                'day',
              )
            ) {
              await updateLastReleaseDate({
                date: customDayjs(lastRelease.date).toDate(),
                incomingHeaders,
              });
              store.dispatch(setShowReleaseModal(true));
              store.dispatch(
                setUser({
                  ...user,
                  last_release_date: lastRelease.date,
                }),
              );
            }
          }
          // Fetch chats data
          const { docs, hasNextPage, active_chat_id, totalDocs } =
            await fetchChatsData(incomingHeaders);

          store.dispatch(
            setChats(
              docs.map((item) => ({
                ...item,
                active: active_chat_id === item.chat_id,
              })),
            ),
          );
          store.dispatch(setHasMoreChats(hasNextPage));
          store.dispatch(setTotalChats(totalDocs));
          const chatsGroups = await fetchChatGroups(incomingHeaders);
          // Dispatch chat groups
          store.dispatch(setChatsGroups(chatsGroups));
          if (active_chat_id) {
            const activeChat = await fetchActiveChat({
              activeChatId: active_chat_id,
              incomingHeaders,
            });

            // Dispatch active chat if exists
            if (activeChat) {
              const { hasMoreMessages = false, ...chat } = activeChat;
              store.dispatch(setActiveChat(chat));
              store.dispatch(setHasMoreMessages(hasMoreMessages));
            } else {
              store.dispatch(setHasMoreMessages(false));
            }
          }

          return {
            props: {},
          };
        } catch (error: any) {
          return handleServerError({
            error,
            ctx,
          });
        }
      },
  );

export default HomePage;
