import Head from 'next/head';
import { GetServerSideProps, GetServerSidePropsResult } from 'next';
import { FC } from 'react';
import axios from 'axios';

import { wrapper } from '@shared/ui/store';
import {
  setHasMoreReleases,
  setReleases,
  setShowReleaseModal,
  setUser,
} from '@shared/ui/store/settings/settings.slice';
import customDayjs from '@shared/ui/libs/dayjs.libs';
import {
  getReleases,
  updateLastReleaseDate,
} from '@shared/ui/services/releases.services';
import { handleServerError } from '@shared/ui/utils/errors.utils';
import { getUser } from '@shared/ui/services/user.services';
import {
  CHAT_MESSAGES_PAGE_SIZE,
  DEFAULT_PAGE_SIZE,
} from '@shared/ui/constants/common.constants';
import { getMessages } from '@shared/ui/services/messages.services';
import { transformMessagesToObject } from '@shared/ui/utils/messages.utils';
import {
  getAvailableDevices,
  getAvailablePlatforms,
} from '@/services/beta-reports.services';
import { createChat, getChats } from '@shared/ui/services/chats.services';
import { setHasMoreMessages } from '@shared/ui/store/chats/chats.slice';
import { pickKeys } from '@shared/ui/utils/common.utils';
import { BETA_REPORTS_URL } from '@shared/ui/constants/env.constants';

import BetaReportsTemplate from '@/components/templates/BetaReportsTemplate';

import { AxiosIncomingClientHeaders } from '@shared/ui/types/axios.types';
import { TemplateErrorProps } from '@shared/ui/interfaces/templates.interfaces';
import { BetaReportsTemplateProps } from '@/components/templates/BetaReportsTemplate/BetaReportsTemplate.props';
import { PlatformEnum } from '@/enums/beta-reports.enum';

const HomePage: FC<{ pageProps: BetaReportsTemplateProps }> = ({
  pageProps,
}) => {
  return (
    <>
      <Head>
        <title>Dish chat - Beta reports</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <BetaReportsTemplate {...pageProps} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps<TemplateErrorProps> =
  wrapper.getServerSideProps(
    // @ts-ignore
    (store) =>
      // @ts-ignore
      async (
        ctx,
      ): Promise<
        GetServerSidePropsResult<
          TemplateErrorProps & Partial<BetaReportsTemplateProps>
        >
      > => {
        try {
          const platform = ctx?.req?.cookies['platform'] || PlatformEnum.ATV;
          const release = ctx?.req?.cookies['release'];
          const device = ctx?.req?.cookies['device'];
          const priority = ctx?.req?.cookies['priority'];
          const dateRange = ctx?.req?.cookies['dateRange'];
          const namespace = `beta_report/${platform.toLowerCase()}`;
          const userEmail =
            ctx?.req?.cookies['userEmail'] ||
            ctx?.req?.headers['x-auth-request-email'];

          if (!userEmail) {
            return {
              redirect: {
                destination: '/403',
                permanent: false,
              },
            };
          }

          const incomingHeaders: AxiosIncomingClientHeaders['incomingHeaders'] =
            {
              ...ctx.req.headers,
              'X-Auth-Request-Email': userEmail,
            };
          const { data } = await axios.get<{ valid: boolean }>(
            `${BETA_REPORTS_URL}/api/access`,
            {
              headers: {
                ...pickKeys({
                  obj: incomingHeaders,
                  keysToPick: [
                    'x-auth-request-email',
                    'cookie',
                    'beta_reports_token',
                  ],
                }),
              },
            },
          );

          if (!data.valid) {
            const [user, releases] = await Promise.all([
              getUser(incomingHeaders),
              getReleases({
                incomingHeaders,
                page: 1,
                limit: DEFAULT_PAGE_SIZE,
              }),
            ]);
            const releasesList = releases?.docs || [];
            store.dispatch(setUser(user));
            store.dispatch(setReleases(releasesList));
            store.dispatch(setHasMoreReleases(!!releases?.hasNextPage));
            const lastRelease = releasesList[0];
            if (lastRelease) {
              const lastReleaseDate = user?.last_release_date;
              if (
                !lastReleaseDate ||
                customDayjs(lastRelease.date).isAfter(
                  customDayjs(lastReleaseDate),
                  'day',
                )
              ) {
                await updateLastReleaseDate({
                  date: customDayjs(lastRelease.date).toDate(),
                  incomingHeaders,
                });
                store.dispatch(setShowReleaseModal(true));
                store.dispatch(
                  setUser({
                    ...user,
                    last_release_date: lastRelease.date,
                  }),
                );
              }
            }
            return {
              props: {
                hasAccess: false,
              },
            };
          }

          const [
            user,
            releases,
            availableDevices = [],
            availablePlatforms = [],
            chats,
          ] = await Promise.all([
            getUser(incomingHeaders),
            getReleases({
              incomingHeaders,
              page: 1,
              limit: DEFAULT_PAGE_SIZE,
            }),
            getAvailableDevices({ incomingHeaders }),
            getAvailablePlatforms({ incomingHeaders }),
            getChats({
              page: 1,
              limit: 1,
              namespace,
              incomingHeaders,
            }),
          ]);
          let activeChat = null;
          if (chats?.docs?.length) {
            activeChat = chats?.docs?.[0];
          } else {
            activeChat = await createChat({ namespace, incomingHeaders });
          }
          const { docs, hasNextPage } = await getMessages({
            chat_id: activeChat?.chat_id,
            page: 1,
            limit: CHAT_MESSAGES_PAGE_SIZE,
            incomingHeaders,
          });
          store.dispatch(setHasMoreMessages(hasNextPage));
          const releasesList = releases?.docs || [];

          // Dispatch user and vault data
          store.dispatch(setUser(user));
          store.dispatch(setReleases(releasesList));
          store.dispatch(setHasMoreReleases(!!releases?.hasNextPage));
          const lastRelease = releasesList[0];
          if (lastRelease) {
            const lastReleaseDate = user?.last_release_date;
            if (
              !lastReleaseDate ||
              customDayjs(lastRelease.date).isAfter(
                customDayjs(lastReleaseDate),
                'day',
              )
            ) {
              await updateLastReleaseDate({
                date: customDayjs(lastRelease.date).toDate(),
                incomingHeaders,
              });
              store.dispatch(setShowReleaseModal(true));
              store.dispatch(
                setUser({
                  ...user,
                  last_release_date: lastRelease.date,
                }),
              );
            }
          }

          return {
            props: {
              availableDevicesOptions: availableDevices.map((item) => ({
                label: item,
                value: item,
              })),
              availablePlatformsOptions: availablePlatforms.map((item) => ({
                label: item,
                value: item,
              })),
              defaultPlatform: platform,
              ...(release && {
                defaultRelease: release,
              }),
              ...(priority && {
                defaultPriority: priority,
              }),
              ...(device && {
                defaultDevice: device,
              }),
              ...(dateRange && {
                defaultDateRange: JSON.parse(dateRange),
              }),
              activeChat: {
                ...activeChat,
                active: true,
                messages: transformMessagesToObject(docs.reverse()),
              },
              hasAccess: true,
            },
          };
        } catch (error: any) {
          return handleServerError({
            error,
            ctx,
          });
        }
      },
  );

export default HomePage;
